### ISSUE TITLE
[api-extractor] Schema not reflecting live branch changes

### ISSUE THREAD

**Issue by samantharamon** [microsoft/json-schemas#125]
Possibly related to https://github.com/microsoft/json-schemas/issues/116.

`enumMemberOrder` was added to [api-extractor/v7/api-extractor.schema.json](https://github.com/microsoft/json-schemas/blob/main/api-extractor/v7/api-extractor.schema.json) in September 2022 (see https://github.com/microsoft/json-schemas/commit/52c734d773ae7d8f6e8670a18fa70bc7d8485c31), but it doesn't appear in https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json.

**Comment by ElizabethSamuel-MSFT** [comment]
@samantharamon I'm seeing enumMemberOrder showing on developer.microsoft.com. Can you confirm? Thx.

**Comment by samantharamon** [comment]
@ElizabethSamuel-MSFT I see it now. Thanks for following up. Closing issue.

**Comment by octogonz** [comment]
Thank you for fixing this!
