### ISSUE TITLE
Parse error in office-js/custom-functions.schema.json

### ISSUE THREAD

**Issue by fds-ssg** [microsoft/json-schemas#25]
Seems to be an unneeded comma on line 139.

`Parse error on line 139:
...                    },
                
-----------------------^
Expecting 'STRING', got '}'`

**Comment by octogonz** [comment]
@Zlatkovsky we've had this same issue reported sometimes for the Rush schemas.  Apparently certain editors are fairly pedantic and won't accept a comment or extra comma in the JSON schema.

I wonder if this repo should have a CI build step that validates the JSON files somehow...

@iclanton FYI

**Comment by Zlatkovsky** [comment]
The particular issue should be fixed now (and should propagate to the live site within the next few hours).
@octogonz , for the CI step:  yes, I think that would be good, but will leave that to you :-)
