### ISSUE TITLE
Support for comments / JSON5 Support for schema?

### ISSUE THREAD

**Issue by dborchers-gc** [microsoft/json-schemas#49]
**Question (the more details, the better)**

I´ve very annoyed that json doenst support comments inside code -.-

I´ve read that the Json Version 5 will support comments inside the code.

Is there any plan to add Json5 Support for the json schema?

https://json5.org/

**Comment by octogonz** [comment]
JSON5 is an encoding used for data files. It is not relevant to the schema. People who author schemas could put comments in their schema files, but then they would need to process them to strip the comments, since tools that load schemas generally do not support JSON5.

**Comment by octogonz** [comment]
To be clear, regular JSON schemas work fine with JSON5 inputs, and even YAML inputs can be validated using a JSON schema. This is because most validators operate on the JavaScript object, not the text file.

**Comment by octogonz** [comment]
BTW you can also put comments in a file with .json file extension. Most editors understand this. When you load the file you use an API such as `jju` that can skip comments. So JSON5 is not strictly necessary.

**Comment by dborchers-gc** [comment]
Okay, thank you very much for the fast comment.

So to be clear - the problem for not supporting comments is the editor? (like. VS Code?)

**Comment by dborchers-gc** [comment]
a practical example in my case:

I uses very big sp-column-formatting JSON Code and i would like to comment them with e.g. TODOs o structure them.

For thsi case i would like to use comments inside the json file for my column-formatting

**Comment by octogonz** [comment]
See "Why do Rush’s JSON config files contain // comments that GitHub shows in red?" on this page for some more details, including ways to get VS Code and GitHub to honor your comments:

https://rushjs.io/pages/help/faq/

**Comment by octogonz** [comment]
This really is a design question for your tool, not the JSON Schema repository.

**Comment by dborchers-gc** [comment]
Okay thank you very much
