### ISSUE TITLE
Unable to export the custom site sharepoint group

### ISSUE THREAD

**Issue by IAMBasantPandey** [microsoft/json-schemas#53]
I am trying to extract the custom SharePoint group using the extract configuration schema method.  Here is the configuration settings I did. 

MySchema.Json Xml File Contents

`{
  "$schema":"https://aka.ms/sppnp-extract-configuration-schema",
  "persistAssetFiles": true,
  "handlers": [
    "Lists",
    "WebSettings",
    "Pages"
  ],
  "pages": {
    "includeAllClientSidePages": true
  },
  "siteSecurity": {
    "includeSiteGroups": true
  }
}`

Get-PnPSiteTemplate -out testtest.xml -Configuration MySchema.json

Somehow testtest.xml file not returning any SharePoint group that I created. Any idea of how can be achieved using configuration schema.

**Comment by octogonz** [comment]
This repo manages JSON schema files only.  It is not the right place to report SharePoint issues.
