### ISSUE TITLE
using openContextMenu in sp/v2 schema

### ISSUE THREAD

**Issue by dborchers-gc** [microsoft/json-schemas#83]
hey @shagra-ms do you have an idea why i cant use the openContextMenu  customRowAction from the v2 sp-formatting schema?

i try this:
`{
                    "elmType": "button",
                    "customRowAction": {
                      "action": "openContextMenu"
                    },
                    "txtContent": "Kontextmenü",
                    "attributes": {
                      "class": "sp-row-button ms-bgColor-neutralLighter ms-fontWeight-semibold"
                    },
                    "style": {
                      "width": "145px",
                      "height": "48px",
                      "margin": "20px 0 10px 0"
                    }
                  }`

but nothing happens when i click on the button.

I didnt find any sample in the docs for that, only for setValue and that works great

**Comment by dborchers-gc** [comment]
i try to use it in view-formatting with hideselection true - just fyi

when i set hideselection to false then in work but then i dont need a button

**Comment by shagra-ms** [comment]
Hi @dborchers-gc, this sounds like a bug. Can you please report this as [https://github.com/SharePoint/sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) ? 

Thanks!

**Comment by shagra-ms** [comment]
I did a quick validation though, but wasn't able to repro this on a List layout. Do share detailed repro steps on the Issue you report in the above repository. Thanks!

**Comment by dborchers-gc** [comment]
I´ve posted a bug on that repo. And you commnadbraProps request was not really what i expected but its cool anyway ;-) I wourld like to add a button to my formatting code to checkIn and checkOut an document and i guess that would be possible with you update but it doesnt seems to be.

So i will try to use openContextMenu intead if its working :-)

**Comment by shagra-ms** [comment]
Thanks for the suggestion @dborchers-gc . We are currently tracking this in our backlog.
